---
title: "R Notebook"
output: html_notebook
---



```{r}
library(ggplot2)
library(data.table)
library(gridExtra)
library(ggpubr)

# read in data processed on HPC
ASV_ranges <- readRDS("../data/processed/sample_range_correlation.rds")[[1]]

empo_1 <- readRDS("../data/processed/empo_ranges/empo_1_sample_range_correlation.rds")[[1]]

empo_2 <- readRDS("../data/processed/empo_ranges/empo_2_sample_range_correlation.rds")[[1]]

empo_3 <- readRDS("../data/processed/empo_ranges/empo_3_sample_range_correlation.rds")[[1]]
#saveRDS( ASV_ranges, "../data/processed/ASV_samples_vs_range_data.rds")

#fwrite(ASV_ranges, "../data/processed/ASV_ranges.csv")


```


```{r}
# range_mod() gets all the components together for plotting range vs. sample type
range_mod <- function(range_dat) {
  # subset data based on minimum range and occupancy
  range_dat <- range_dat[range_coord > 0 & group_count > 1]
  
  # calculate linear model
  range_mod <-
    lm(log(range_coord + 1) ~ log(group_count), data = range_dat)
  
  # run anova
  range_anova <- summary(range_mod)
  
  # predict confidence intervals
  conf_int <-
    predict(range_mod, interval = "confidence", level = 0.95)
  
  out <- list(range_dat, conf_int, range_mod, range_anova)
  names(out) <- c("data", "conf_interval", "range_mod", "anova_sum")
  
  return(out)
  
}


# run on the sample types
empo_1_mod <- range_mod(empo_1)
empo_2_mod <- range_mod(empo_2)
empo_3_mod <- range_mod(empo_3)

sample_type_mod <- range_mod(ASV_ranges)

```


# Plot

```{r}
hist1 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = group_count))+
  labs(x = "Number of Sample Types", title =  "Histogram: Number of Sample Types")

hist2 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = range_coord))+
  labs(x = "Range in Latitude", title ="Histogram: Number of Sample Types")


hist3 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = log(group_count +1 )))+
  labs(x = "Number of Sample Types", title =  "Histogram: Number of Sample Types")

hist4 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = log(range_coord+1)))+
  labs(x = "Range in Latitude", title ="Histogram: Number of Sample Types")
hist4

ggsave(hist1, "../outputs/figures/n_samples_hist.png")
ggsave(hist2, "../outputs/figures/range_lat_hist.png")
ggsave(hist3, "../outputs/figures/log_n_samples_hist.png")
ggsave(hist4, "../outputs/figures/log_range_lat_hist.png")


```


# Plot EMPO ASV Range Correlation
```{r}

plot_range_cor <- function(plot_mod, description = NULL) {
  p <-
    ggplot(plot_mod$data,  aes(x = group_count, y = log(range_coord + 1))) +
    # points
    #geom_jitter(width = 0.2, height = 3, alpha = 0.3)+
    
    # density
    stat_bin_2d(aes(fill = log(..count..))) +
    scale_fill_viridis_c() +
    
    # scales and labels
    theme(panel.grid.minor = element_blank()) +
    scale_x_continuous(breaks = seq_len(max(plot_mod$data$group_count)),
                       expand = expansion(c(0, .01))) +
    labs(title = "Global Range vs. Distribution Across Sample Types ",
         caption = paste(
           "P =",
           signif(plot_mod$anova_sum$coefficients[8], 3),
           "   ",
           "R^2 = ",
           signif(plot_mod$anova_sum$r.squared, 3)
         )) +
    labs(color = "Latitude Range",
         x = "Number of Sample Types",
         y = "Global Range in Latitude") +
    theme_classic() +
    #theme( panel.background = element_rect(fill = "white",
    #                         colour = "darkgray",
    #                        size = 0.5, linetype = "solid"))+
    
    
    # trend line and confidence interval
    # geom_abline( slope = coefficients( plot_mod$range_mod )[2],
    #             intercept = coefficients( plot_mod$range_mod )[1] ) +
    geom_ribbon(
      aes(
        ymin = plot_mod$conf_interval[, 2],
        ymax = plot_mod$conf_interval[, 3]
      ),
      color = "blue",
      fill = "blue",
      alpha = 0.2
    )
  
  p
  # save plot
  ggsave(
    filename = paste0(
      "../outputs/figures/",
      description,
      "_range_correlation.png"
    ),
    p,
    width = 10
  )
  
}

plot_range_cor(sample_type_mod, "sample_type")
plot_range_cor(empo_2_mod, "empo_2")
plot_range_cor(empo_3_mod, "empo_3")


```

# Plot Mean Range Correlation By Habitat


```{r}
# ASVs present in each habitat determined using the script ASV_habitat.R

# read in list of ASVs present in each habitat
hab_asvs <- readRDS("../data/processed/habitat_ASVS.rds")

# make a data.frame of ASV ranges/group counts for each habitat for plotting and comparison
hab_ranges_list <- lapply(names(hab_asvs), function(hab) {
  empo_3_hab <- empo_3[OTU_ID %in% hab_asvs[[hab]]]
  empo_3_hab$habitat <- hab
  return(empo_3_hab)
})
# bind together
hab_ranges_dt <- do.call("rbind", hab_ranges_list)


# Boxplots
# set up comparisons for means
my_comparisons <- list( c(1, 2), c(2, 3), c(1, 3) )

p <-
  ggplot(hab_ranges_dt, aes(x = habitat, y = range_coord, fill = habitat)) +
  geom_boxplot(outlier.shape = NA) +
  #geom_jitter(width = .2) +
  theme_pubr() +
  ylab("ASV Latitudinal Range") +
  labs(title = "ASV ranges by Habitat", caption = "T-test") +
  
  stat_compare_means(comparisons = my_comparisons, method = "t.test") # Add pairwise comparisons p-value
p

ggsave("../outputs/figures/ASV_ranges_by_habitat.png", plot = p)

aov_out   <- aov(lm(Value ~ Habitat, nest_ind))
tukey_out <- TukeyHSD(aov_out)
print(tukey_out)


# Range correlation plots and pull out range and group count mean/sd for each habitat
hab_range_summary <- hab_ranges_dt[ , .(mean_range = mean(range_coord),
                                        sd_range = sd(range_coord),
                                        mean_types = mean(group_count),
                                        sd_types = sd(group_count)),
                                    by = habitat]
hab_range_summary

```

